const promotions_chicos = {
  promo_25off100: {
      formValue: '25off100',
      formText: '$25 off $100',
      dataTrack: '25Off100',
      h4: '$25 Off Your Purchase of $100 or More',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_crew: {
      formValue: 'crew',
      formText: '$ Card Rewards',
      dataTrack: '$CardRewards',
      h4: 'Redeem Your $20 Beyond Fabulous&trade; Reward',
      moustache18: 'When You Spend $100 or More',
      moustache15: 'Now Through May 1, 2016',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_chand: {
      formValue: 'chand',
      formText: '$ Card Handout',
      dataTrack: '$CardHandout',
      h4: 'Redeem Your $20 Beyond Fabulous&trade; Reward',
      moustache18: 'When You Spend $100 or More',
      moustache15: 'Now Through May 1, 2016',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_flon: {
      formValue: 'flon',
      formText: 'Flash Sale - Online Only',
      dataTrack: 'Flash_OO',
      eyeBrow: '24-Hour Flash Sale | Online Only',
      h4: '50% Off Your Highest-Priced Item When You Spend $100 or More',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_flbo: {
      formValue: 'flbo',
      formText: 'Flash Sale - In Boutiques & Online',
      dataTrack: 'Flash_BO',
      eyeBrow: '24-Hour Flash Sale | In Boutiques &amp; Online',
      h4: '50% Off Your Highest-Priced Item When You Spend $100 or More',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_3in1: {
      formValue: '3in1',
      formText: '3 Deals 1 Day',
      dataTrack: '3Deals1Day',
      eyeBrow: '6PM - Midnight (EST) | Online Only',
      h4: '50% Off Your Highest-Priced Item When You Spend $100 Or More',
      h4_2: 'XX% Off Entire Purchase',
      useCode: 'XXXXX',
      useCode_2: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_poff: {
      formValue: 'poff',
      formText: 'XX% Off Select Styles (Boutiques & Online)',
      dataTrack: 'PCTOFF_SS_BO',
      eyeBrow: 'Today Only',
      h4: 'Take an Extra 60% Off Select Styles',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_psel: {
      formValue: 'psel',
      formText: 'XX% Off Select Styles (Online Only)',
      dataTrack: 'PCTOFF_SS_OO',
      eyeBrow: 'Today, Online Only',
      h4: 'Take an Extra 60% Off Select Styles',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_fpb: {
      formValue: 'fpb',
      formText: 'Full-Priced Bogo',
      dataTrack: 'FP_BOGO',
      h4: 'Buy One, Get One 50% Off Full-Priced Styles',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_bb: {
      formValue: 'bb',
      formText: 'Bottoms Bogo',
      dataTrack: 'Bottoms_BOGO',
      h4: 'Buy One, Get One 50% Off Full-Priced Pants & Jeans',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_tb: {
      formValue: 'tb',
      formText: 'Tops Bogo',
      dataTrack: 'Tops_BOGO',
      h4: 'Buy One, Get One 50% Off Full-Priced Tops, Jackets, & Sweaters',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_epoff: {
      formValue: 'epoff',
      formText: 'Extra % Off',
      dataTrack: 'Extra_XXPCT_OFF',
      bigEyeBrow: 'Sale',
      h4: 'We\'ve Taken An Extra XX% Off Select Already-Reduced Styles',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_fsall: {
      formValue: 'fsall',
      formText: 'Free Shipping All Orders',
      dataTrack: 'FREE_SHIP',
      h4: 'Free Shipping On All Purchases',
      moustache18: 'Passport Members Always Enjoy Free Shipping',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_fs100: {
      formValue: 'fs100',
      formText: 'Free Shipping on $100+',
      dataTrack: 'FREE_SHIP_100',
      h4: 'Free Shipping On $100 Or More',
      moustache18: 'Passport Members Always Enjoy Free Shipping',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_nm: {
      formValue: 'nm',
      formText: 'New Markdowns',
      dataTrack: 'NewMarkdowns',
      h4: 'New Markdowns Just Taken',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
  },
  promo_utp: {
      formValue: 'promo_utp',
      formText: 'Up to XX% Off',
      dataTrack: 'UpTo_XXPCTOFF',
      bigEyeBrow: 'Sale',
      h4: 'Up to XX% Off Select Styles',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_5ep: {
      formValue: '5ep',
      formText: 'XX+5 Entire Purchase',
      dataTrack: 'XXPCTOFF_PLUS5_EP',
      h4: 'XX% Off Entire Purchase',
      moustache18: 'Passport Members Take An Extra 5% Off',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_5epo: {
      formValue: '5epo',
      formText: 'XX+5 Entire Purchase Online Only',
      dataTrack: 'XXPCTOFF_PLUS5_EP_OO',
      h4: 'XX% Off Entire Purchase',
      moustache18: 'Passport Members Take An Extra 5% Off',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_caep: {
      formValue: 'caep',
      formText: 'CA XX+5 Entire Purchase',
      dataTrack: 'CAN_XXPCTOFF_EP',
      h4: 'XX% Off Entire Purchase',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_5fp: {
      formValue: '5fp',
      formText: 'XX+5 Full-Priced',
      dataTrack: 'XXPCTOFF_PLUS5_FP',
      h4: 'XX% Off Full-Priced Styles',
      moustache18: 'Passport Members Take An Extra 5% Off',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_5fpo: {
      formValue: '5fpo',
      formText: 'ONLINE ONLY | XX Full-Priced Styles',
      dataTrack: 'XXPCTOFF_PLUS5_FPO',
      eyebrow: 'Online Only',
      h4: 'XX% Off Full-Priced Styles',
      moustache18: 'Passport Members Take An Extra 5% Off',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_cafp: {
      formValue: 'cafp',
      formText: 'CA XX+5 Full-Priced',
      dataTrack: 'CAN_XXPCTOFF_FP',
      h4: 'XX% Off Full-Priced Styles',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_pfp: {
      formValue: 'pfp',
      formText: '40_30_20 Full-Priced',
      dataTrack: 'XXPCTOFF_FP',
      h4: 'XX% Off',
      moustache18: 'Four Or More Full-Priced Items',
      useCode: 'XXXXX',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_ptjs: {
      formValue: 'ptjs',
      formText: 'XX% Off Full-Priced Tops, Jackets & Sweaters',
      dataTrack: 'XXPCT_OFF_FPTops',
      h4: 'Take XX% Off Full-Priced Tops, Jackets, & Sweaters',
      useCode: 'XXXXX',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_cas: {
      formValue: 'cas',
      formText: 'CA Shipping + Free Duties',
      dataTrack: 'CAN_10Ship75',
      h4: '$9.95 CAD Standard Shipping On Orders Over $75 CAD + Free Duties',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
  promo_oc: {
      formValue: 'oc',
      formText: 'Online Clearance',
      dataTrack: 'Onlince_Clearance',
      eyeBrow: 'Online Only',
      h4: '19.98 & Up Clearance Sweaters',
      ctaText: 'Shop Now',
      ctaLink: '/store/',
      detailsCopy: 'Cupcake ipsum dolor sit amet dessert. Cookie tart pastry. Cookie carrot cake chocolate cake chupa chups pastry macaroon gingerbread. Cheesecake apple pie powder jelly beans sweet roll lollipop cookie. Pie gummi bears icing. Halvah soufflé pudding brownie jujubes biscuit sweet roll chupa chups tart. Donut jujubes chocolate bar pudding biscuit fruitcake jujubes pastry sugar plum. Marzipan sweet roll halvah oat cake. Gummies sweet roll cheesecake halvah jelly cotton candy.',
  },
}
export default promotions_chicos;
